openapi: 3.0.1
info:
  title: '@jupiterone/graph-fastly'
  description: A graph conversion tool for https://www.fastly.com
  x-cortex-git:
    github:
      repository: JupiterOne/graph-fastly
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-fastly'
  x-cortex-service-groups:
    - tier-4
